security:
  user:
    password: password

  admin:
    password: admin

    spring:
      datasource:
        url: jdbc:h2:mem:mytest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        platform: h2

      # enable H2 web console and set url for web console
      # http://localhost:8080/console
      h2:
        console:
          enabled: true
          path: /console

spring.mvc.view:
  prefix: /WEB-INF/views/
  suffix: .jsp


my:
   servers:
       - dev.bar.com
       - foo.bar.com

#server:
#  contextPath: helloPage


spring:
  profiles.active: default
---
spring:
  profiles: default

ymlImport:
  wow: 10
  such: so
  very: true

---
spring:
   profiles: unit-test
ymlImport:
  wow: 6