INSERT INTO requests VALUES (1, 'Sergii', 'Create Jenkins unit test job', 'sergantty@gmai.com', 'Stas', 'Open', 2);
INSERT INTO requests VALUES (2, 'Stas', 'Introduce Ansible usage', 'kronverk@hotmail.com', 'Sergii', 'Open', 1);
INSERT INTO requests VALUES (3, 'Sergii', 'Create Jenkins unit test job', 'sergantty@gmai.com', 'Stas', 'Open', 2);
INSERT INTO requests VALUES (4, 'Stas', 'Introduce Ansible usage', 'kronverk@hotmail.com', 'Sergii', 'Open', 1);
INSERT INTO requests VALUES (5, 'Sergii', 'Create Jenkins unit test job', 'sergantty@gmai.com', 'Stas', 'Open', 2);
INSERT INTO requests VALUES (6, 'Stas', 'Introduce Ansible usage', 'kronverk@hotmail.com', 'Sergii', 'Open', 1);
INSERT INTO requests VALUES (7, 'Sergii', 'Create Jenkins unit test job', 'sergantty@gmai.com', 'Stas', 'Open', 2);
INSERT INTO requests VALUES (8, 'Stas', 'Introduce Ansible usage', 'kronverk@hotmail.com', 'Sergii', 'Open', 1);
INSERT INTO requests VALUES (9, 'Sergii', 'Create Jenkins unit test job', 'sergantty@gmai.com', 'Stas', 'Open', 2);
INSERT INTO requests VALUES (10, 'Stas', 'Introduce Ansible usage', 'kronverk@hotmail.com', 'Sergii', 'Open', 1);